### ISSUE TITLE
Multicast et UDP

### ISSUE THREAD

**Issue by techexo** [betonniere/freeteuse#7]
Bonjour @betonniere

Je n'arrive pas à me connecter depuis mon OnePlus sur une Freebox Mini 4k, alors que j'y arrive depuis une autre application (FreeTelec pour ne pas la nommer).

J'ai lu dans d'autres tickets que ça pouvait être un problème d'initialisation de connexion via multicast, puis UDP, qui pouvait être filtrée par un routeur (par exemple).

Ma configuration est une Freebox Server en mode bridge, vers un routeur ethernet/wifi. Vers où puis-je aller chercher pour savoir quels ports libérer ou rediriger sur mon serveur ? De quoi a vraiment besoin l'appli pour fonctionner ?

Merci beaucoup !

**Comment by betonniere** [comment]
Bonjour, 


L'application Freeteuse a été conçue pour fonctionner sur Freebox V6 (Révolution). Elle ne fonctionne pas sur Mini4k (pour le moment). 
En attendant sa disponibilité pour les boîtes Android, le mieux est d'utiliser l'application Google (https://play.google.com/store/apps/details?id=com.google.android.tv.remote). 


Yannick Le Roux 

----- Mail original -----

De: "Eloi Coutant" <notifications@github.com> 
À: "betonniere/freeteuse" <freeteuse@noreply.github.com> 
Cc: "betonniere" <bellepoule.dev@free.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Mercredi 12 Décembre 2018 20:49:07 
Objet: [betonniere/freeteuse] Multicast et UDP (#7) 


Bonjour @betonniere 
Je n'arrive pas à me connecter depuis mon OnePlus sur une Freebox Mini 4k, alors que j'y arrive depuis une autre application (FreeTelec pour ne pas la nommer). 
J'ai lu dans d'autres tickets que ça pouvait être un problème d'initialisation de connexion via multicast, puis UDP, qui pouvait être filtrée par un routeur (par exemple). 
Ma configuration est une Freebox Server en mode bridge, vers un routeur ethernet/wifi. Vers où puis-je aller chercher pour savoir quels ports libérer ou rediriger sur mon serveur ? De quoi a vraiment besoin l'appli pour fonctionner ? 
Merci beaucoup !

**Comment by techexo** [comment]
Oups, j'ai lu trop vite la description de l'application ! Merci pour la réponse rapide 🙂
